#ifndef SHROOM_REST_ROUTER_H
#define SHROOM_REST_ROUTER_H

typedef enum ShroomRestRoute {
  SHROOM_REST_ROUTE_NOT_FOUND = 0,
  SHROOM_REST_ROUTE_HEALTH,
  SHROOM_REST_ROUTE_ACCOUNT_REGISTER,
  SHROOM_REST_ROUTE_ACCOUNT_LOGIN,
  SHROOM_REST_ROUTE_ACCOUNT_REFRESH,
  SHROOM_REST_ROUTE_ACCOUNT_LOGOUT,
  SHROOM_REST_ROUTE_ACCOUNT_ME
} ShroomRestRoute;

ShroomRestRoute ShroomRestClassifyRoute(const char* method, const char* path);

#endif
