#ifndef SHROOM_CONFIG_H
#define SHROOM_CONFIG_H

#define SHROOM_MAX_PARTICIPANTS 256u
#define SHROOM_MAX_SPLIT_PIECES 4
#define SHROOM_MAX_PLAYER_ENTITIES (SHROOM_MAX_PARTICIPANTS * SHROOM_MAX_SPLIT_PIECES)
#define SHROOM_MAX_SPORES 4096
#define SHROOM_MAX_NAME_LENGTH 32u

#define SHROOM_WORLD_WIDTH 6000.0f
#define SHROOM_WORLD_HEIGHT 6000.0f
#define SHROOM_WORLD_REPLICATION_INTEREST_RADIUS 2200.0f

#define SHROOM_ZONE_CENTER_RADIUS 900.0f
#define SHROOM_ZONE_MID_RADIUS 2000.0f

#define SHROOM_DEFAULT_PLAYER_MASS 96.0f
#define SHROOM_BOT_COUNT 18
#define SHROOM_BOT_FLOOR 4u
#define SHROOM_MAX_PLAYABLE_PARTICIPANTS SHROOM_MAX_PARTICIPANTS
#define SHROOM_BOT_TARGET_TOTAL 16u
#define SHROOM_BOT_REAL_PLAYER_WEIGHT 2u
#define SHROOM_BOT_TACTICAL_COOLDOWN_CONSERVATIVE 1.75f
#define SHROOM_BOT_TACTICAL_COOLDOWN_AGGRESSIVE 0.75f
#define SHROOM_BOT_TACTICAL_COOLDOWN_OBJECTIVE 1.25f
#define SHROOM_BOT_POWERUP_SEARCH_RADIUS 900.0f
#define SHROOM_BOT_SPLIT_REACH 360.0f
#define SHROOM_BOT_EJECT_PRESSURE_RANGE 700.0f
#define SHROOM_DECAY_MASS_THRESHOLD (SHROOM_DEFAULT_PLAYER_MASS * 6.0f)
#define SHROOM_DECAY_RATE_CENTER_PER_SECOND 0.06f
#define SHROOM_DECAY_RATE_MID_PER_SECOND 0.03f
#define SHROOM_DECAY_RATE_OUTER_PER_SECOND 0.015f
#define SHROOM_MAX_PLAYER_MASS (SHROOM_DEFAULT_PLAYER_MASS * 20.0f)
#define SHROOM_IDLE_PENALTY_GRACE_SECONDS 8.0f
#define SHROOM_IDLE_PENALTY_BLEED_PER_SECOND (SHROOM_DEFAULT_PLAYER_MASS * 0.5f / 60.0f)
/* Inputs are normalized by the server. Keep this above analog noise and safely below length 1. */
#define SHROOM_IDLE_PENALTY_MOVEMENT_THRESHOLD_SQR 0.01f
#define SHROOM_SPEED_FLOOR_FACTOR 0.60f

// Game modes
typedef enum ShroomGameMode {
  SHROOM_GAME_MODE_FFA = 0,       // Free-for-all (default)
  SHROOM_GAME_MODE_TEAMS_2V2,     // 2v2 teams
  SHROOM_GAME_MODE_TEAMS_3V3,     // 3v3 teams
  SHROOM_GAME_MODE_TEAMS_4V4,     // 4v4 teams
  SHROOM_GAME_MODE_BATTLE_ROYALE, // Last player standing with shrinking zone
  SHROOM_GAME_MODE_KING_OF_HILL,  // Control center zone for points
  SHROOM_GAME_MODE_MASS_RACE,     // First to reach target mass wins
  SHROOM_GAME_MODE_COUNT
} ShroomGameMode;

#define SHROOM_MAX_TEAMS 8u
#define SHROOM_TEAM_NAME_LENGTH 32u

// Keep small colonies nimble while letting large colonies become catchable.
#define SHROOM_MIN_PLAYER_SPEED 132.0f
#define SHROOM_MAX_PLAYER_SPEED 252.0f
#define SHROOM_PLAYER_SPEED_MASS_SCALE 0.42f

// More spores with slightly lower value smooths early growth and recovery pacing.
#define SHROOM_SPORE_TARGET_COUNT 1100
#define SHROOM_SPORE_VALUE 7

#define SHROOM_MAX_POWERUPS 8
#define SHROOM_POWERUP_TYPE_SPEED 1u
#define SHROOM_POWERUP_TYPE_SHIELD 2u
#define SHROOM_POWERUP_TYPE_MAGNET 3u
#define SHROOM_POWERUP_TYPE_DECAY_IMMUNE 4u
#define SHROOM_POWERUP_TYPE_COUNT 4u
#define SHROOM_POWERUP_RADIUS 18.0f
#define SHROOM_POWERUP_RESPAWN_SECONDS 24.0f
#define SHROOM_POWERUP_SPEED_MULTIPLIER 1.6f
#define SHROOM_POWERUP_SPEED_SECONDS 5.0f
#define SHROOM_POWERUP_SHIELD_SECONDS 4.0f
#define SHROOM_POWERUP_MAGNET_SECONDS 6.0f
#define SHROOM_POWERUP_MAGNET_RADIUS 280.0f
#define SHROOM_POWERUP_MAGNET_PULL_SPEED 520.0f
#define SHROOM_POWERUP_DECAY_IMMUNE_SECONDS 7.0f

#define SHROOM_EJECT_MASS_VALUE 28.0f
#define SHROOM_EJECT_COOLDOWN_SECONDS 0.45f
#define SHROOM_EJECT_COST_FRACTION 0.10f
#define SHROOM_EJECT_MIN_MASS (SHROOM_DEFAULT_PLAYER_MASS * 1.75f)
#define SHROOM_EJECT_IMPULSE_RANGE 72.0f

// Tighten consume rules and reduce snowballing from single catches.
#define SHROOM_CONSUME_MASS_ADVANTAGE 1.18f
#define SHROOM_CENTER_CONSUME_ADVANTAGE 1.08f
#define SHROOM_CONSUME_MASS_GAIN_FACTOR 0.58f
#define SHROOM_BOUNDARY_CONSUME_MARGIN 100.0f

// Give fresh spawns more breathing room before re-entering contested space.
#define SHROOM_SPAWN_SAFE_DISTANCE 440.0f
#define SHROOM_SPAWN_MEDIUM_SAFE_DISTANCE 320.0f
#define SHROOM_SPAWN_MIN_SAFE_DISTANCE 220.0f
#define SHROOM_SPAWN_PADDING 120.0f
#define SHROOM_SPAWN_SMALL_LOBBY_PLAYERS 16u
#define SHROOM_SPAWN_MEDIUM_LOBBY_PLAYERS 40u
#define SHROOM_SPAWN_MIN_RADIUS (SHROOM_ZONE_MID_RADIUS + SHROOM_SPAWN_PADDING)
#define SHROOM_SPAWN_MAX_BAND_WIDTH 900.0f
#define SHROOM_SPAWN_MIN_BAND_WIDTH 220.0f
#define SHROOM_PLAYER_SPAWN_PROTECTION_SECONDS 2.0f

/* Splitting — large colonies may split before the hard mass cap. */
#define SHROOM_SPLIT_MIN_MASS (SHROOM_DEFAULT_PLAYER_MASS * 4.0f)
#define SHROOM_SPLIT_MASS_THRESHOLD SHROOM_SPLIT_MIN_MASS
/* Mass lost to ejection cost on split. Net mass after split = parent_mass * (1 - this).
 * The lost mass is discarded (not spawned as a decay spore) for simplicity —
 * split is positioned as a tactical tradeoff, not a free lunch. */
#define SHROOM_SPLIT_MASS_LOSS_FRACTION 0.05f
#define SHROOM_SPLIT_MERGE_SECONDS 10.0f
#define SHROOM_SPLIT_PROTECTION_SECONDS 1.4f
#define SHROOM_SPLIT_IMPULSE_SPEED 220.0f
#define SHROOM_SPLIT_IMPULSE_DECAY 2.5f
#define SHROOM_SPLIT_HOLD_SECONDS 0.6f

#define SHROOM_SERVER_TICK_RATE 30.0f
#define SHROOM_MATCH_DURATION_SECONDS 600.0f
#define SHROOM_MATCH_RESULTS_SECONDS 30.0f
#define SHROOM_MATCH_PODIUM_COUNT 3u

/* King of the Hill: one colony scores per second regardless of its piece count. */
#define SHROOM_KOTH_SCORE_PER_SECOND 1.0f
#define SHROOM_KOTH_TARGET_SCORE 100.0f

/* Lobby configuration */
#define SHROOM_MAX_LOBBIES 8u
#define SHROOM_LOBBY_DEFAULT_COUNT 4u
#define SHROOM_LOBBY_MAX_NAME_LENGTH 32u
#define SHROOM_LOBBY_DYNAMIC_EMPTY_TIMEOUT_S 120u

#endif
