#ifndef SHROOM_CONFIG_H
#define SHROOM_CONFIG_H

#define SHROOM_MAX_PLAYERS 128
#define SHROOM_MAX_SPORES 4096

#define SHROOM_WORLD_WIDTH 6000.0f
#define SHROOM_WORLD_HEIGHT 6000.0f

#define SHROOM_ZONE_CENTER_RADIUS 900.0f
#define SHROOM_ZONE_MID_RADIUS 2000.0f

#define SHROOM_DEFAULT_PLAYER_MASS 100.0f
#define SHROOM_BOT_COUNT 18
#define SHROOM_MIN_PLAYER_SPEED 120.0f
#define SHROOM_MAX_PLAYER_SPEED 260.0f
#define SHROOM_PLAYER_SPEED_MASS_SCALE 0.35f

#define SHROOM_SPORE_TARGET_COUNT 900
#define SHROOM_SPORE_VALUE 8

#define SHROOM_CONSUME_MASS_ADVANTAGE 1.15f
#define SHROOM_CONSUME_MASS_GAIN_FACTOR 0.70f
#define SHROOM_SPAWN_SAFE_DISTANCE 340.0f

#define SHROOM_SERVER_TICK_RATE 30.0f

#endif
