#ifndef SHROOM_IMGUI_TEST_IMCONFIG_H
#define SHROOM_IMGUI_TEST_IMCONFIG_H

#define IMGUI_TEST_ENGINE_ENABLE_CAPTURE 0
#define IMGUI_TEST_ENGINE_ENABLE_IMPLOT 0
#define IMGUI_TEST_ENGINE_ENABLE_COROUTINE_STDTHREAD_IMPL 1

#include "imgui_te_imconfig.h"

#endif
